name = "ACTRSimulators"
uuid = "c655e612-5123-41dd-bf97-8af606dbe7c1"
version = "0.3.7"
authors = ["itsdfish"]

[deps]
ACTRModels = "c095b0ea-a6ca-5cbd-afed-dbab2e976880"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiscreteEventsLite = "8b1724b8-7d2d-4f3a-bca2-6234a697fafb"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[extensions]
GtkExt = "Gtk"

[compat]
ACTRModels = "v0.9.0, 0.10, 0.11, 0.12, 0.13"
Cairo = "v1.0.0"
CodeTracking = "2.0.0, 3"
ConcreteStructs = "v0.2.0"
DataStructures = "v0.18.0"
DiscreteEventsLite = "v0.1.0"
Distributions = "0.25.0"
Gtk = "v1.1.0"
Printf = "1"
Test = "1.11.0"
julia = "^1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
